// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC47xrbUgdwvbmGFRTSrRIfO1HWtE2HV9o',
    appId: '1:94694985944:web:73ac108cc7a320e28c47ad',
    messagingSenderId: '94694985944',
    projectId: 'flash-card-8d80f',
    authDomain: 'flash-card-8d80f.firebaseapp.com',
    storageBucket: 'flash-card-8d80f.firebasestorage.app',
    measurementId: 'G-YXW611KHVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ0moQIzEU7krkap_Xg_8BI7Pmhvdigek',
    appId: '1:94694985944:android:94416ac17240e85f8c47ad',
    messagingSenderId: '94694985944',
    projectId: 'flash-card-8d80f',
    storageBucket: 'flash-card-8d80f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGovTCW6Ey1N1N0jrTCB_0Vn7XuAYkzMw',
    appId: '1:94694985944:ios:09f9f11c7db4ff6b8c47ad',
    messagingSenderId: '94694985944',
    projectId: 'flash-card-8d80f',
    storageBucket: 'flash-card-8d80f.firebasestorage.app',
    iosBundleId: 'com.example.flashcard',
  );
}
